[@Resources\Vars.inc]
VisualizerType=Vector
ImageUnderlay=1
ImageUnderlayName=#SKINSPATH#ModularVisualizer\@Resources\UserImages\Alena Aenami.jpg
ImageUnderlayFileName=Alena Aenami
[@Resources\Vars\Vector.inc]
LayerCount=3
VectorBands=20
VectorWidth=1920
MinimumHeight=4
Layer1Height=300
Layer2Height=120
Layer3Height=50
Layer4Height=50
BarType=Solid
Angle=0
[@Resources\Vars\Vector\Solid.inc]
Layer1Color=254,0,0,30
Layer2Color=255,0,4,106
Layer3Color=255,18,22,255
Layer4Color=255,0,0