[Variables]
;@ | Name MirrorXY

;?Info | Name MirrorX | Description Settings for MirrorX | Link 0
 = 

;?Integer | Name First X-Offset
Group1XOffset=0

;?Integer | Name First Y-Offset
Group1YOffset=0

;?Integer | Name Second X-Offset
Group2XOffset=-1000

;?Integer | Name Second Y-Offset
Group2YOffset=28

;?Integer | Name Third X-Offset
Group3XOffset=0

;?Integer | Name Third Y-Offset
Group3YOffset=28

;?Integer | Name Fourth X-Offset
Group4XOffset=-1000

;?Integer | Name Fourth Y-Offset
Group4YOffset=56

;?List | Name X-Flip | Options Group1,Group1XFlip; Group2,Group2XFlip; Group3,Group3XFlip; Group4,Group4XFlip
Group1XFlip=0
Group2XFlip=0
Group3XFlip=0
Group4XFlip=0

;?List | Name Y-Flip | Options Group1,Group1YFlip; Group2,Group2YFlip; Group3,Group3YFlip; Group4,Group4YFlip
Group1YFlip=0
Group2YFlip=0
Group3YFlip=0
Group4YFlip=0
