[Variables]
;@ | Name MirrorY

;?Info | Name MirrorY | Description Settings for MirrorY | Link 0
 = 

;?Integer | Name First X-Offset
Group1XOffset=0

;?Integer | Name Second X-Offset
Group2XOffset=0

;?Integer | Name First Y-Offset
Group1YOffset=0

;?Integer | Name Second Y-Offset
Group2YOffset=0

;?List | Name X-Flip | Options Group1,Group1XFlip; Group2,Group2XFlip
Group1XFlip=0
Group2XFlip=0

;?List | Name Y-Flip | Options Group1,Group1YFlip; Group2,Group2YFlip
Group1YFlip=0
Group2YFlip=0
