[Variables]
VisualizerType=Bar
ImageUnderlay=0
ImageUnderlayName=#SKINSPATH#ModularVisualizer\@Resources\UserImages\Alena Aenami.jpg
ImageUnderlayFileName=Alena Aenami
ImageOverlay=0
ImageOverlayName=
ImageOverlayFileName=
DeviceName=Microphone (2- MAONO AU-BM10)
DeviceID={0.0.1.00000000}.{93cb243a-ea98-4710-825f-c6aaef3a225b}
BoostRate=1
;?RadioButton | Name Audio Source | Options Output,DefaultOutput; Input,DefaultInput; DeviceID,"ID: [#DeviceID]"
AnalyzerPort=DefaultOutput
AnalyzerPortIsID=0
