
[Measure1]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=MainFinalOutput

[Measure2]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=MainFinalOutput

[Measure3]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=MainFinalOutput

[Measure4]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=MainFinalOutput

[Measure5]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=MainFinalOutput

[Measure6]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=MainFinalOutput

[Measure7]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=MainFinalOutput

[Measure8]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=MainFinalOutput

[Measure9]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=MainFinalOutput

[Measure10]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=MainFinalOutput

[Measure11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=MainFinalOutput

[Measure12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=MainFinalOutput

[Measure13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=MainFinalOutput

[Measure14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=MainFinalOutput

[Measure15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=MainFinalOutput

[Measure16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=MainFinalOutput

[Measure17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=MainFinalOutput

[Measure18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=MainFinalOutput

[Measure19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=MainFinalOutput

[Measure20]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=MainFinalOutput

