
[Measure1]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=MainFinalOutput

[Measure2]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=MainFinalOutput

[Measure3]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=MainFinalOutput

[Measure4]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=MainFinalOutput

[Measure5]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=MainFinalOutput

[Measure6]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=MainFinalOutput

[Measure7]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=MainFinalOutput

[Measure8]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=MainFinalOutput

[Measure9]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=MainFinalOutput

[Measure10]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=MainFinalOutput

[Measure11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=MainFinalOutput

[Measure12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=MainFinalOutput

[Measure13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=MainFinalOutput

[Measure14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=MainFinalOutput

[Measure15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=MainFinalOutput

[Measure16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=MainFinalOutput

[Measure17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=MainFinalOutput

[Measure18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=MainFinalOutput

[Measure19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=MainFinalOutput

[Measure20]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=MainFinalOutput

[Measure21]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=21
Channel=Auto
HandlerName=MainFinalOutput

[Measure22]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=22
Channel=Auto
HandlerName=MainFinalOutput

[Measure23]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=23
Channel=Auto
HandlerName=MainFinalOutput

[Measure24]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=24
Channel=Auto
HandlerName=MainFinalOutput

[Measure25]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=25
Channel=Auto
HandlerName=MainFinalOutput

[Measure26]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=26
Channel=Auto
HandlerName=MainFinalOutput

[Measure27]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=27
Channel=Auto
HandlerName=MainFinalOutput

[Measure28]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=28
Channel=Auto
HandlerName=MainFinalOutput

[Measure29]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=29
Channel=Auto
HandlerName=MainFinalOutput

[Measure30]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=30
Channel=Auto
HandlerName=MainFinalOutput

[Measure31]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=31
Channel=Auto
HandlerName=MainFinalOutput

[Measure32]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=32
Channel=Auto
HandlerName=MainFinalOutput

[Measure33]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=33
Channel=Auto
HandlerName=MainFinalOutput

[Measure34]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=34
Channel=Auto
HandlerName=MainFinalOutput

[Measure35]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=35
Channel=Auto
HandlerName=MainFinalOutput

[Measure36]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=36
Channel=Auto
HandlerName=MainFinalOutput

[Measure37]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=37
Channel=Auto
HandlerName=MainFinalOutput

[Measure38]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=38
Channel=Auto
HandlerName=MainFinalOutput

[Measure39]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=39
Channel=Auto
HandlerName=MainFinalOutput

[Measure40]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=40
Channel=Auto
HandlerName=MainFinalOutput

[Measure41]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=41
Channel=Auto
HandlerName=MainFinalOutput

[Measure42]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=42
Channel=Auto
HandlerName=MainFinalOutput

[Measure43]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=43
Channel=Auto
HandlerName=MainFinalOutput

[Measure44]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=44
Channel=Auto
HandlerName=MainFinalOutput

[Measure45]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=45
Channel=Auto
HandlerName=MainFinalOutput

[Measure46]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=46
Channel=Auto
HandlerName=MainFinalOutput

[Measure47]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=47
Channel=Auto
HandlerName=MainFinalOutput

[Measure48]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=48
Channel=Auto
HandlerName=MainFinalOutput

[Measure49]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=49
Channel=Auto
HandlerName=MainFinalOutput

[Measure50]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=50
Channel=Auto
HandlerName=MainFinalOutput

[Measure51]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=51
Channel=Auto
HandlerName=MainFinalOutput

[Measure52]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=52
Channel=Auto
HandlerName=MainFinalOutput

[Measure53]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=53
Channel=Auto
HandlerName=MainFinalOutput

[Measure54]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=54
Channel=Auto
HandlerName=MainFinalOutput

[Measure55]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=55
Channel=Auto
HandlerName=MainFinalOutput

[Measure56]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=56
Channel=Auto
HandlerName=MainFinalOutput

[Measure57]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=57
Channel=Auto
HandlerName=MainFinalOutput

[Measure58]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=58
Channel=Auto
HandlerName=MainFinalOutput

[Measure59]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=59
Channel=Auto
HandlerName=MainFinalOutput

[Measure60]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=60
Channel=Auto
HandlerName=MainFinalOutput

[Measure61]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=61
Channel=Auto
HandlerName=MainFinalOutput

[Measure62]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=62
Channel=Auto
HandlerName=MainFinalOutput

[Measure63]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=63
Channel=Auto
HandlerName=MainFinalOutput

[Measure64]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=64
Channel=Auto
HandlerName=MainFinalOutput

[Measure65]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=65
Channel=Auto
HandlerName=MainFinalOutput

[Measure66]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=66
Channel=Auto
HandlerName=MainFinalOutput

[Measure67]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=67
Channel=Auto
HandlerName=MainFinalOutput

[Measure68]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=68
Channel=Auto
HandlerName=MainFinalOutput

[Measure69]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=69
Channel=Auto
HandlerName=MainFinalOutput

[Measure70]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=70
Channel=Auto
HandlerName=MainFinalOutput

[Measure71]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=71
Channel=Auto
HandlerName=MainFinalOutput

[Measure72]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=72
Channel=Auto
HandlerName=MainFinalOutput

[Measure73]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=73
Channel=Auto
HandlerName=MainFinalOutput

[Measure74]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=74
Channel=Auto
HandlerName=MainFinalOutput

[Measure75]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=75
Channel=Auto
HandlerName=MainFinalOutput

[Measure76]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=76
Channel=Auto
HandlerName=MainFinalOutput

[Measure77]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=77
Channel=Auto
HandlerName=MainFinalOutput

[Measure78]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=78
Channel=Auto
HandlerName=MainFinalOutput

[Measure79]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=79
Channel=Auto
HandlerName=MainFinalOutput

[Measure80]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=80
Channel=Auto
HandlerName=MainFinalOutput

[Measure81]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=81
Channel=Auto
HandlerName=MainFinalOutput

[Measure82]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=82
Channel=Auto
HandlerName=MainFinalOutput

[Measure83]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=83
Channel=Auto
HandlerName=MainFinalOutput

[Measure84]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=84
Channel=Auto
HandlerName=MainFinalOutput

[Measure85]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=85
Channel=Auto
HandlerName=MainFinalOutput

[Measure86]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=86
Channel=Auto
HandlerName=MainFinalOutput

[Measure87]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=87
Channel=Auto
HandlerName=MainFinalOutput

[Measure88]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=88
Channel=Auto
HandlerName=MainFinalOutput

[Measure89]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=89
Channel=Auto
HandlerName=MainFinalOutput

[Measure90]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=90
Channel=Auto
HandlerName=MainFinalOutput

[Measure91]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=91
Channel=Auto
HandlerName=MainFinalOutput

[Measure92]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=92
Channel=Auto
HandlerName=MainFinalOutput

[Measure93]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=93
Channel=Auto
HandlerName=MainFinalOutput

[Measure94]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=94
Channel=Auto
HandlerName=MainFinalOutput

[Measure95]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=95
Channel=Auto
HandlerName=MainFinalOutput

[Measure96]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=96
Channel=Auto
HandlerName=MainFinalOutput

[Measure97]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=97
Channel=Auto
HandlerName=MainFinalOutput

[Measure98]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=98
Channel=Auto
HandlerName=MainFinalOutput

[Measure99]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=99
Channel=Auto
HandlerName=MainFinalOutput

[Measure100]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=100
Channel=Auto
HandlerName=MainFinalOutput

[Measure101]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=101
Channel=Auto
HandlerName=MainFinalOutput

[Measure102]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=102
Channel=Auto
HandlerName=MainFinalOutput

[Measure103]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=103
Channel=Auto
HandlerName=MainFinalOutput

[Measure104]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=104
Channel=Auto
HandlerName=MainFinalOutput

[Measure105]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=105
Channel=Auto
HandlerName=MainFinalOutput

[Measure106]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=106
Channel=Auto
HandlerName=MainFinalOutput

[Measure107]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=107
Channel=Auto
HandlerName=MainFinalOutput

[Measure108]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=108
Channel=Auto
HandlerName=MainFinalOutput

[Measure109]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=109
Channel=Auto
HandlerName=MainFinalOutput

[Measure110]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=110
Channel=Auto
HandlerName=MainFinalOutput

[Measure111]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=111
Channel=Auto
HandlerName=MainFinalOutput

[Measure112]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=112
Channel=Auto
HandlerName=MainFinalOutput

[Measure113]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=113
Channel=Auto
HandlerName=MainFinalOutput

[Measure114]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=114
Channel=Auto
HandlerName=MainFinalOutput

[Measure115]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=115
Channel=Auto
HandlerName=MainFinalOutput

[Measure116]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=116
Channel=Auto
HandlerName=MainFinalOutput

[Measure117]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=117
Channel=Auto
HandlerName=MainFinalOutput

[Measure118]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=118
Channel=Auto
HandlerName=MainFinalOutput

[Measure119]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=119
Channel=Auto
HandlerName=MainFinalOutput

[Measure120]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=120
Channel=Auto
HandlerName=MainFinalOutput

[Measure121]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=121
Channel=Auto
HandlerName=MainFinalOutput

[Measure122]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=122
Channel=Auto
HandlerName=MainFinalOutput

[Measure123]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=123
Channel=Auto
HandlerName=MainFinalOutput

[Measure124]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=124
Channel=Auto
HandlerName=MainFinalOutput

[Measure125]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=125
Channel=Auto
HandlerName=MainFinalOutput

[Measure126]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=126
Channel=Auto
HandlerName=MainFinalOutput

[Measure127]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=127
Channel=Auto
HandlerName=MainFinalOutput

[Measure128]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=128
Channel=Auto
HandlerName=MainFinalOutput

[Measure129]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=129
Channel=Auto
HandlerName=MainFinalOutput

[Measure130]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=130
Channel=Auto
HandlerName=MainFinalOutput

[Measure131]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=131
Channel=Auto
HandlerName=MainFinalOutput

[Measure132]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=132
Channel=Auto
HandlerName=MainFinalOutput

[Measure133]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=133
Channel=Auto
HandlerName=MainFinalOutput

[Measure134]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=134
Channel=Auto
HandlerName=MainFinalOutput

[Measure135]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=135
Channel=Auto
HandlerName=MainFinalOutput

[Measure136]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=136
Channel=Auto
HandlerName=MainFinalOutput

[Measure137]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=137
Channel=Auto
HandlerName=MainFinalOutput

[Measure138]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=138
Channel=Auto
HandlerName=MainFinalOutput

[Measure139]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=139
Channel=Auto
HandlerName=MainFinalOutput

[Measure140]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=140
Channel=Auto
HandlerName=MainFinalOutput

[Measure141]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=141
Channel=Auto
HandlerName=MainFinalOutput

[Measure142]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=142
Channel=Auto
HandlerName=MainFinalOutput

[Measure143]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=143
Channel=Auto
HandlerName=MainFinalOutput

[Measure144]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=144
Channel=Auto
HandlerName=MainFinalOutput

[Measure145]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=145
Channel=Auto
HandlerName=MainFinalOutput

[Measure146]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=146
Channel=Auto
HandlerName=MainFinalOutput

[Measure147]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=147
Channel=Auto
HandlerName=MainFinalOutput

[Measure148]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=148
Channel=Auto
HandlerName=MainFinalOutput

[Measure149]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=149
Channel=Auto
HandlerName=MainFinalOutput

[Measure150]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=150
Channel=Auto
HandlerName=MainFinalOutput

[Measure151]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=151
Channel=Auto
HandlerName=MainFinalOutput

[Measure152]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=152
Channel=Auto
HandlerName=MainFinalOutput

[Measure153]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=153
Channel=Auto
HandlerName=MainFinalOutput

[Measure154]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=154
Channel=Auto
HandlerName=MainFinalOutput

[Measure155]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=155
Channel=Auto
HandlerName=MainFinalOutput

[Measure156]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=156
Channel=Auto
HandlerName=MainFinalOutput

[Measure157]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=157
Channel=Auto
HandlerName=MainFinalOutput

[Measure158]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=158
Channel=Auto
HandlerName=MainFinalOutput

[Measure159]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=159
Channel=Auto
HandlerName=MainFinalOutput

[Measure160]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=160
Channel=Auto
HandlerName=MainFinalOutput

[Measure161]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=161
Channel=Auto
HandlerName=MainFinalOutput

[Measure162]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=162
Channel=Auto
HandlerName=MainFinalOutput

[Measure163]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=163
Channel=Auto
HandlerName=MainFinalOutput

[Measure164]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=164
Channel=Auto
HandlerName=MainFinalOutput

[Measure165]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=165
Channel=Auto
HandlerName=MainFinalOutput

[Measure166]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=166
Channel=Auto
HandlerName=MainFinalOutput

[Measure167]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=167
Channel=Auto
HandlerName=MainFinalOutput

[Measure168]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=168
Channel=Auto
HandlerName=MainFinalOutput

[Measure169]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=169
Channel=Auto
HandlerName=MainFinalOutput

[Measure170]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=170
Channel=Auto
HandlerName=MainFinalOutput

[Measure171]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=171
Channel=Auto
HandlerName=MainFinalOutput

[Measure172]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=172
Channel=Auto
HandlerName=MainFinalOutput

[Measure173]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=173
Channel=Auto
HandlerName=MainFinalOutput

[Measure174]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=174
Channel=Auto
HandlerName=MainFinalOutput

[Measure175]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=175
Channel=Auto
HandlerName=MainFinalOutput

[Measure176]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=176
Channel=Auto
HandlerName=MainFinalOutput

[Measure177]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=177
Channel=Auto
HandlerName=MainFinalOutput

[Measure178]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=178
Channel=Auto
HandlerName=MainFinalOutput

[Measure179]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=179
Channel=Auto
HandlerName=MainFinalOutput

[Measure180]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=180
Channel=Auto
HandlerName=MainFinalOutput

[Measure181]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=181
Channel=Auto
HandlerName=MainFinalOutput

[Measure182]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=182
Channel=Auto
HandlerName=MainFinalOutput

[Measure183]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=183
Channel=Auto
HandlerName=MainFinalOutput

[Measure184]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=184
Channel=Auto
HandlerName=MainFinalOutput

[Measure185]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=185
Channel=Auto
HandlerName=MainFinalOutput

[Measure186]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=186
Channel=Auto
HandlerName=MainFinalOutput

[Measure187]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=187
Channel=Auto
HandlerName=MainFinalOutput

[Measure188]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=188
Channel=Auto
HandlerName=MainFinalOutput

[Measure189]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=189
Channel=Auto
HandlerName=MainFinalOutput

[Measure190]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=190
Channel=Auto
HandlerName=MainFinalOutput

[Measure191]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=191
Channel=Auto
HandlerName=MainFinalOutput

[Measure192]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=192
Channel=Auto
HandlerName=MainFinalOutput

[Measure193]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=193
Channel=Auto
HandlerName=MainFinalOutput

[Measure194]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=194
Channel=Auto
HandlerName=MainFinalOutput

[Measure195]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=195
Channel=Auto
HandlerName=MainFinalOutput

[Measure196]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=196
Channel=Auto
HandlerName=MainFinalOutput

[Measure197]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=197
Channel=Auto
HandlerName=MainFinalOutput

[Measure198]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=198
Channel=Auto
HandlerName=MainFinalOutput

[Measure199]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=199
Channel=Auto
HandlerName=MainFinalOutput

[Measure200]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=200
Channel=Auto
HandlerName=MainFinalOutput

[Measure201]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=201
Channel=Auto
HandlerName=MainFinalOutput

[Measure202]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=202
Channel=Auto
HandlerName=MainFinalOutput

[Measure203]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=203
Channel=Auto
HandlerName=MainFinalOutput

[Measure204]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=204
Channel=Auto
HandlerName=MainFinalOutput

[Measure205]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=205
Channel=Auto
HandlerName=MainFinalOutput

[Measure206]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=206
Channel=Auto
HandlerName=MainFinalOutput

[Measure207]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=207
Channel=Auto
HandlerName=MainFinalOutput

[Measure208]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=208
Channel=Auto
HandlerName=MainFinalOutput

[Measure209]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=209
Channel=Auto
HandlerName=MainFinalOutput

[Measure210]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=210
Channel=Auto
HandlerName=MainFinalOutput

[Measure211]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=211
Channel=Auto
HandlerName=MainFinalOutput

[Measure212]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=212
Channel=Auto
HandlerName=MainFinalOutput

[Measure213]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=213
Channel=Auto
HandlerName=MainFinalOutput

[Measure214]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=214
Channel=Auto
HandlerName=MainFinalOutput

[Measure215]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=215
Channel=Auto
HandlerName=MainFinalOutput

[Measure216]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=216
Channel=Auto
HandlerName=MainFinalOutput

[Measure217]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=217
Channel=Auto
HandlerName=MainFinalOutput

[Measure218]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=218
Channel=Auto
HandlerName=MainFinalOutput

[Measure219]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=219
Channel=Auto
HandlerName=MainFinalOutput

[Measure220]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=220
Channel=Auto
HandlerName=MainFinalOutput

[Measure221]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=221
Channel=Auto
HandlerName=MainFinalOutput

[Measure222]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=222
Channel=Auto
HandlerName=MainFinalOutput

[Measure223]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=223
Channel=Auto
HandlerName=MainFinalOutput

[Measure224]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=224
Channel=Auto
HandlerName=MainFinalOutput

[Measure225]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=225
Channel=Auto
HandlerName=MainFinalOutput

[Measure226]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=226
Channel=Auto
HandlerName=MainFinalOutput

[Measure227]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=227
Channel=Auto
HandlerName=MainFinalOutput

[Measure228]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=228
Channel=Auto
HandlerName=MainFinalOutput

[Measure229]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=229
Channel=Auto
HandlerName=MainFinalOutput

[Measure230]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=230
Channel=Auto
HandlerName=MainFinalOutput

[Measure231]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=231
Channel=Auto
HandlerName=MainFinalOutput

[Measure232]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=232
Channel=Auto
HandlerName=MainFinalOutput

[Measure233]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=233
Channel=Auto
HandlerName=MainFinalOutput

[Measure234]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=234
Channel=Auto
HandlerName=MainFinalOutput

[Measure235]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=235
Channel=Auto
HandlerName=MainFinalOutput

[Measure236]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=236
Channel=Auto
HandlerName=MainFinalOutput

[Measure237]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=237
Channel=Auto
HandlerName=MainFinalOutput

[Measure238]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=238
Channel=Auto
HandlerName=MainFinalOutput

[Measure239]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=239
Channel=Auto
HandlerName=MainFinalOutput

[Measure240]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=240
Channel=Auto
HandlerName=MainFinalOutput

