[Variables]
;@Default | Name AudioAnalyzer

;?Integer | Name Maximum Sensititvity
MaxSensitivity=45

;?Integer | Name Minimum Sensitivity
MinSensitivity=9

;?Integer | Name Rising Delay | Description in milliseconds
Attack=0

;?Integer | Name Falling Delay | Description in milliseconds
Decay=0

;?Integer | Name Smoothing Level | Description How smooth your visuallizer is
BlurRadius=1

;?String | Name Channel | Description Auto::C::FL::FR::BL::BR::BC::SL::SR
Channel=Auto

;?String | Name Window Function
WindowFunction=Kaiser
