[Variables]

;@ | Name Vector

;?Integer | Name LayerCount
LayerCount=4

;?Integer | Name Points
VectorBands=5

;?String | Name Width
VectorWidth=300

;?String | Name Width
MinimumHeight=4

;?Integer | Name Layer1 Height
Layer1Height=300

;?Integer | Name Layer2 Height
Layer2Height=120

;?Integer | Name Layer3 Height
Layer3Height=110

;?Integer | Name Layer4 Height
Layer4Height=50

;?RadioButton | Name Color Mode | Options Solid; Gradient
BarType=Solid

;?Integer | Name Angle
Angle=0

@includeVectorColors=Vector\[#BarType].inc
